language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

install:
  - yarn install
  - yarn global add codecov
script:
  - yarn test --coverage
  - codecov
