language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

install:
  - npm i -g codecov
  - npm install
script:
  - yarn test --coverage
  - codecov
