version: '3'
services:
  iceberg-lighthouse:
    build: '.'
    ports:
      - 6000:3000
    environment:
      - HOST=influxdb
    volumes:
      - ./config.json:/usr/src/lighthouse/config.json
      - ./volume/reports:/usr/src/lighthouse/reports
      - ./volume/logs:/usr/src/lighthouse/logs
  influxdb:
    image: 'influxdb:latest'
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./volume/influxdb:/var/lib/influxdb
  chronograf:
    image: 'chronograf:latest'
    ports:
      - 8888:8888
    volumes:
      - ./volume/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
